spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # OAuth2 (나중에 활성화)
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            scope:
#              - email
#              - profile

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 604800000  # 7일
  refresh-expiration: 604800000 # 7일

server:
  port: 8080

upload:
  path: ${UPLOAD_PATH:./uploads}
  url-prefix: ${UPLOAD_URL_PREFIX:http://localhost:8080/uploads}
